.github/workflows/sync-fork.yml

- Adding `sync-fork.yml` workflow

Adding `sync-fork.yml` workflow

---

.github/workflows/codeql.yml
.github/workflows/sync-fork.yml

- CodeQL also runs on PR's to main branch

Testing `sync-fork.yml`

---

.github/workflows/sync-fork.yml

Testing CODEOWNERS

---

.github/workflows/ci.yml

- Adding ci.yml for build purposes

Testing CI

---

.github/workflows/sync-branch.yml

Testing sync-branch

---

.github/dependabot.yml
.github/workflows/pr-auto-assign.yml

- Adding PR auto assign
- Adding assignees to dependabot

Adding PR auto assign and assignees to dependabot

---

README.md
cloudbuild.yml
sources/Dockerfile
sources/src/main/java/com/google/solutions/jitaccess/core/adapters/ResourceManagerAdapter.java
sources/src/main/java/com/google/solutions/jitaccess/core/services/RoleDiscoveryService.java
sources/src/main/java/com/google/solutions/jitaccess/web/RuntimeConfiguration.java
sources/src/main/java/com/google/solutions/jitaccess/web/RuntimeEnvironment.java
sources/src/test/java/com/google/solutions/jitaccess/core/services/TestRoleDiscoveryService.java

- Filter project discovery based on a tag (optional)
- Bump base image version
- Create cloudbuild.yml

Filter project discovery with tag and define pipeline

---

cloudbuild.yaml

Fix cloudbuild

---

.github/workflows/codeql.yml

- Removing dependabot exception from `codeql.yml`

Removing dependabot exception from `codeql.yml`

---

cloudbuild.yaml

- Adding Binary Authorization script instead of previous method

Adding Binary Authorization script instead of previous method2

---

cloudbuild.yaml

- Fix cloudbuild severity check to check fix status

Fix cloudbuild severity check to check fix status

---

cloudbuild.yaml

- Fix cloudbuild attestation step

Fix cloudbuild attestation step

---

cloudbuild.yaml

- Fix cloudbuild sign-and-create command

Fix cloudbuild sign-and-create command

---

cloudbuild.yaml

- Fix cloudbuild severity command

Fix cloudbuild severity command

---

cloudbuild.yaml

- Fix cloudbuild severity command exit

Fix cloudbuild severity command exit

---

sources/src/main/resources/notifications/RequestActivation.html

- Fix typo in request email
- "actviate" -> "activate"

Fix typo in request email

---

.github/workflows/pr-labeler.yml

rollback pr labeler

---

cloudbuild.yaml

Add wait-for in cloudbuild

---

.github/pr-labeler.yml
cloudbuild.yaml

Fix wait-for in cloudbuild

---

cloudbuild.yaml

Add build pipeline timeout

---

sources/pom.xml
sources/src/main/java/com/google/solutions/jitaccess/core/catalog/project/AssetInventoryRepository.java
sources/src/main/java/com/google/solutions/jitaccess/core/catalog/project/MpaProjectRoleCatalog.java
sources/src/main/java/com/google/solutions/jitaccess/core/catalog/project/PolicyAnalyzerRepository.java
sources/src/main/java/com/google/solutions/jitaccess/core/catalog/project/ProjectActivationRequest.java
sources/src/main/java/com/google/solutions/jitaccess/core/catalog/project/ProjectRoleActivator.java
sources/src/main/java/com/google/solutions/jitaccess/core/clients/ResourceManagerClient.java
sources/src/main/java/com/google/solutions/jitaccess/core/notifications/NotificationService.java

- Cleanup code and remove bad WithSpan annotations

Cleanup code and remove bad WithSpan annotations

---

sources/pom.xml
sources/src/main/java/com/google/solutions/jitaccess/core/catalog/project/MpaProjectRoleCatalog.java
sources/src/main/java/com/google/solutions/jitaccess/core/catalog/project/PolicyAnalyzerRepository.java
sources/src/main/java/com/google/solutions/jitaccess/core/catalog/project/ProjectActivationRequest.java
sources/src/main/java/com/google/solutions/jitaccess/core/catalog/project/ProjectRoleActivator.java
sources/src/main/java/com/google/solutions/jitaccess/core/notifications/NotificationService.java

- Fix WithSpan annotations
- Bump opentelemetry version

Fix WithSpan annotations
